### ISSUE TITLE
1.0.2 tag/release is missing on GitHub

### ISSUE THREAD

**Issue by diox** [peterbe/hashin#197]
Hi,

I noticed that 1.0.2 has no corresponding tag or release on GitHub. Could you make one to make it easier to see what changed since 1.0.1 ? Thanks!

**Comment by hartwork** [comment]
@peterbe how about commit 520f98f33234e68bb15e190baaa19dcbb88cfbd4 for the tag?

```bash
git tag -m 'version 1.0.2' 1.0.2 520f98f33234e68bb15e190baaa19dcbb88cfbd4
git push origin 1.0.2
```

**Comment by peterbe** [comment]
Done.

**Comment by hartwork** [comment]
@peterbe the release page for 1.0.2 at https://github.com/peterbe/hashin/releases is still missing

**Comment by hartwork** [comment]
> @peterbe the release page for 1.0.2 at https://github.com/peterbe/hashin/releases is still missing

Done: https://github.com/peterbe/hashin/releases/tag/1.0.2
